/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        bg:                  'var(--color-bg)',
        surface:             'var(--color-surface)',
        'surface-raised':    'var(--color-surface-raised)',
        sidebar:             'var(--color-sidebar)',
        'sidebar-surface':   'var(--color-sidebar-surface)',
        toolbar:             'var(--color-toolbar)',
        ink:                 'var(--color-ink)',
        'ink-muted':         'var(--color-ink-muted)',
        'ink-faint':         'var(--color-ink-faint)',
        'ink-on-sidebar':    'var(--color-ink-on-sidebar)',
        'ink-sidebar-muted': 'var(--color-ink-sidebar-muted)',
        'ink-on-primary':    'var(--color-ink-on-primary)',
        primary:             'var(--color-primary)',
        'primary-hover':     'var(--color-primary-hover)',
        'primary-subtle':    'var(--color-primary-subtle)',
        accent:              'var(--color-accent)',
        'accent-subtle':     'var(--color-accent-subtle)',
        success:             'var(--color-success)',
        warning:             'var(--color-warning)',
        error:               'var(--color-error)',
        info:                'var(--color-info)',
        border:              'var(--color-border)',
        'border-strong':     'var(--color-border-strong)',
        'border-sidebar':    'var(--color-border-sidebar)',
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'Fira Code', 'Courier New', 'monospace'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['0.6875rem', { lineHeight: '1.25' }],
        xs:    ['0.75rem',   { lineHeight: '1.25' }],
        sm:    ['0.875rem',  { lineHeight: '1.4' }],
        base:  ['1rem',      { lineHeight: '1.6' }],
        md:    ['1.125rem',  { lineHeight: '1.4' }],
        lg:    ['1.25rem',   { lineHeight: '1.25' }],
        xl:    ['1.5rem',    { lineHeight: '1.25' }],
        '2xl': ['1.875rem',  { lineHeight: '1.25' }],
      },
      borderRadius: {
        xs:   '3px',
        sm:   '6px',
        md:   '8px',
        lg:   '10px',
        pill: '9999px',
      },
      boxShadow: {
        sm: '0 1px 3px oklch(0 0 0 / 0.09), 0 1px 2px oklch(0 0 0 / 0.06)',
        md: '0 4px 8px oklch(0 0 0 / 0.10), 0 2px 4px oklch(0 0 0 / 0.06)',
      },
      transitionDuration: {
        fast:   '120ms',
        normal: '200ms',
      },
      transitionTimingFunction: {
        'ease-out': 'cubic-bezier(0.25, 0, 0.1, 1)',
      },
      zIndex: {
        dropdown:         100,
        sticky:           200,
        'modal-backdrop': 300,
        modal:            400,
        toast:            500,
        tooltip:          600,
      },
    },
  },
  plugins: [],
}
